# config.yaml
general:
  data_location: '/mnt/ceph_rbd/ae-dynamical/Re100test/'
  # data_location: '/Users/jpage2/code/jax-cfd-data-gen/Re100test/'
  weight_location: '/mnt/ceph_rbd/ae-dynamical/weights/'
  file_prefix: 'vort_traj.'
  n_files: 2
  n_fields: 2 # 1 for vorticity, 2 for velocity
  loss_fn: 'FINE' # select COARSE or FINE  

grid:
  Nx: 128
  Ny: 128
  Re: 100.0

training:
  filter_size: 8
  n_grow: 3
  T_unroll: 1.0
  M_substep: 8 # dt_assim = M_substep * dt_stable
  batch_size: 32
  lr_mse: 0.0001
  lr_traj: 0.00001
  nval: 5
  n_mse_steps: 5
  n_trajectory_steps: 100
  alpha: 0.5 # split MSE vs traj unroll loss 
